spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=Ravi@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081